# Dependabot will run on day 21 of each month at 01:41 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "41 1 21 * *"
    open-pull-requests-limit: 15

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "41 1 21 * *"
    open-pull-requests-limit: 20
    assignees:
      - "klein0r"
    versioning-strategy: "increase"
